export type PeriodEvent={owner?:string;owner_color?:string;id:string;title:string;start:string;end:string;division:string;status:string};
export const dayMs=86400000;
export function dayNumber(value:string){return Date.parse(value+'T00:00:00Z')/dayMs}
export function dayString(value:number){return new Date(value*dayMs).toISOString().slice(0,10)}
export function divisionClass(value:string){return value==='대학원'?'division-grad':value==='학부'?'division-undergrad':'division-dept'}
export function periodLabel(event:PeriodEvent,compact=false){if(event.start===event.end)return compact?event.start.slice(8):event.start.replaceAll('-','.');if(compact&&event.start.slice(0,7)===event.end.slice(0,7))return event.start.slice(8)+'–'+event.end.slice(8);if(compact&&event.start.slice(0,4)===event.end.slice(0,4))return event.start.slice(5).replace('-','.')+'–'+event.end.slice(5).replace('-','.');return event.start.replaceAll('-','.')+'–'+event.end.replaceAll('-','.')}
export function monthBounds(month:string){const start=dayNumber(month+'-01'),d=new Date(start*dayMs);d.setUTCMonth(d.getUTCMonth()+1);return {start,end:d.getTime()/dayMs-1}}
export function intersectsMonth(event:PeriodEvent,month:string){const b=monthBounds(month);return dayNumber(event.start)<=b.end&&dayNumber(event.end)>=b.start}
export function monthColor(year:number,index:number){const palette=['#195787','#197e9a','#278d88','#548749','#859324','#b18a17','#ce8722','#d2693c','#b64658','#a84075','#825099','#6057a5','#426aaa','#247a82','#668344'];return palette[((year-2026)*12+index)%15<0?((year-2026)*12+index)%15+15:((year-2026)*12+index)%15]}
export function calendarWeeks<T extends PeriodEvent>(month:string,events:T[]){const {start,end}=monthBounds(month),gridStart=start-new Date(start*dayMs).getUTCDay();return Array.from({length:Math.ceil((end-gridStart+1)/7)},(_,week)=>{const from=gridStart+week*7,to=from+6,lanes:number[]=[];const segments=events.filter(e=>dayNumber(e.start)<=Math.min(to,end)&&dayNumber(e.end)>=Math.max(from,start)).sort((a,b)=>a.start.localeCompare(b.start)||b.end.localeCompare(a.end)||a.id.localeCompare(b.id)).map(event=>{const first=Math.max(dayNumber(event.start),from,start),last=Math.min(dayNumber(event.end),to,end);let lane=lanes.findIndex(until=>until<first);if(lane<0)lane=lanes.length;lanes[lane]=last;return {event,first:first-from,last:last-from,lane,continuesBefore:dayNumber(event.start)<first,continuesAfter:dayNumber(event.end)>last}});return {from,days:Array.from({length:7},(_,i)=>({date:dayString(from+i),day:new Date((from+i)*dayMs).getUTCDate(),outside:from+i<start||from+i>end})),segments,lanes:lanes.length}})}
