'use client';
import {useRef,useState,useEffect,useLayoutEffect} from 'react';
import {holidayName,holidayYearAvailable,ownerColor,ownerName} from './calendar-labels';
import {useDragScroll} from './use-drag-scroll';
import {calendarWeeks,dayNumber,dayString,divisionClass,intersectsMonth,monthBounds,monthColor,periodLabel,type PeriodEvent} from './schedule-math';
function shiftMonth(month:string,delta:number){const [y,m]=month.split('-').map(Number);const date=new Date(Date.UTC(y,m-1+delta,1));return date.toISOString().slice(0,7)}
export function ScheduleOverview<T extends PeriodEvent>({events,anchorMonth,onOpen}:{events:T[];anchorMonth:string;onOpen:(event:T)=>void}){
 const ref=useRef<HTMLDivElement>(null);useDragScroll(ref);
 const [size,setSize]=useState({available:1000,name:260}),[position,setPosition]=useState(0),[rangeLabel,setRangeLabel]=useState('');
 const rows=[...events].sort((a,b)=>a.start.localeCompare(b.start)||a.end.localeCompare(b.end)||a.id.localeCompare(b.id));
 const firstMonth=rows.reduce((v,e)=>e.start.slice(0,7)<v?e.start.slice(0,7):v,shiftMonth(anchorMonth,-36));
 const lastMonth=rows.reduce((v,e)=>e.end.slice(0,7)>v?e.end.slice(0,7):v,shiftMonth(anchorMonth,36));
 const from=monthBounds(firstMonth).start,to=monthBounds(lastMonth).end,total=to-from+1;
 const focusFrom=monthBounds(shiftMonth(anchorMonth,-10)).start,focusTo=monthBounds(shiftMonth(anchorMonth,10)).end;
 const scale=Math.max(size.available/(focusTo-focusFrom+1),size.available<650?2.5:1.3),width=total*scale;
 const months:{key:string;start:number;end:number}[]=[];let cursor=firstMonth;
 while(cursor<=lastMonth){const b=monthBounds(cursor);months.push({key:cursor,...b});cursor=dayString(b.end+1).slice(0,7)}
 function sync(){const el=ref.current;if(!el)return;const max=el.scrollWidth-el.clientWidth;setPosition(max?el.scrollLeft/max*1000:0);const start=from+Math.floor(el.scrollLeft/scale),end=Math.min(to,start+Math.ceil(size.available/scale)-1);setRangeLabel(dayString(start).slice(0,7).replace('-','.')+' — '+dayString(end).slice(0,7).replace('-','.'))}
 function center(){const el=ref.current;if(!el)return;const mobile=size.available<650;const target=mobile?monthBounds(anchorMonth).start:focusFrom;el.scrollLeft=Math.max(0,(target-from)*scale);sync()}
 useLayoutEffect(()=>{const el=ref.current;if(!el)return;const measure=()=>{const name=el.querySelector<HTMLElement>('.overview-name')?.offsetWidth||260;setSize({available:Math.max(1,el.clientWidth-name),name})};measure();const observer=new ResizeObserver(measure);observer.observe(el);return()=>observer.disconnect()},[]);
 useLayoutEffect(()=>{center()},[anchorMonth,firstMonth,size.available,scale]);
 const current=monthBounds(anchorMonth);
 return <section className="overview"><div className="overview-caption"><strong>전체 기간표</strong><span>{rangeLabel} · {rows.length}개 행사</span><button className="overview-today" onClick={center}>이번 달 중심</button></div><OwnerLegend events={rows}/><div className="overview-scroll" ref={ref} onScroll={sync} tabIndex={0} aria-label="전체 행사 기간표, 좌우 드래그로 이동"><div className="overview-grid" style={{width:width+size.name}}><div className="overview-header"><div className="overview-name">행사 · 기간</div><div className="overview-months" style={{width}}>{months.map(m=><div key={m.key} className={m.key===anchorMonth?'overview-current':''} style={{width:(m.end-m.start+1)*scale,background:monthColor(Number(m.key.slice(0,4)),Number(m.key.slice(5))-1)}}>{m.key.replace('-','.')}{m.key===anchorMonth&&<small>이번 달</small>}</div>)}</div></div>{rows.map(event=><div className={'overview-row '+divisionClass(event.division)+(event.status==='완료'?' is-complete':'')} key={event.id}><button className="overview-name" onClick={()=>onOpen(event)}><strong>{event.title}</strong><small>{periodLabel(event)} · {Math.round(dayNumber(event.end)-dayNumber(event.start))+1}일</small><span>{event.division} · {event.status}</span></button><div className="overview-track" style={{width}}><div className="overview-current-band" style={{left:(current.start-from)*scale,width:(current.end-current.start+1)*scale}}/>{months.map(m=><i key={m.key} style={{left:(m.start-from)*scale}}/>)}<button className={'overview-bar'+(event.status==='진행 중'?' is-progress':'')} style={{background:ownerColor(event.owner,event.owner_color),left:(dayNumber(event.start)-from)*scale,width:Math.max(5,(dayNumber(event.end)-dayNumber(event.start)+1)*scale)}} onClick={()=>onOpen(event)} aria-label={event.title+' '+periodLabel(event)+' 상세 보기'} title={event.title+' · '+periodLabel(event)+' · 담당자: '+ownerName(event.owner)}><span>{event.title}</span></button></div></div>)}{!rows.length&&<p className="calendar-empty">선택한 조건에 맞는 행사가 없습니다.</p>}</div></div><div className="overview-navigation"><span>{firstMonth.replace('-','.')}</span><input type="range" min="0" max="1000" step="1" value={position} aria-label="전체 기간 이동" onChange={e=>{const el=ref.current;if(el){el.scrollLeft=Number(e.target.value)/1000*(el.scrollWidth-el.clientWidth);sync()}}}/><span>{lastMonth.replace('-','.')}</span></div></section>
}
function OwnerLegend({events}:{events:PeriodEvent[]}){const names=Array.from(new Set(events.map(e=>ownerName(e.owner)))).sort();return names.length?<div className="owner-legend" aria-label="담당자 색상 안내">{names.map(name=><span key={name}><i style={{background:ownerColor(name,events.find(e=>ownerName(e.owner)===name)?.owner_color)}}/>{name}</span>)}</div>:null}
export function FoldedCalendar<T extends PeriodEvent>(props:{defaultOpen?:boolean;viewMode?:string;month:string;events:T[];onOpen:(event:T)=>void;onExpand:()=>void}){const [open,setOpen]=useState(!!props.defaultOpen||(props.viewMode==='모두 펼침'&&props.events.length>0));useEffect(()=>{setOpen(!!props.defaultOpen||(props.viewMode==='모두 펼침'&&props.events.length>0))},[props.month,props.defaultOpen,props.viewMode,props.events.length>0]);return <div className={'folded-calendar'+(open?' is-open':'')}><button className="calendar-toggle" aria-expanded={open} aria-controls={'calendar-'+props.month} onClick={()=>setOpen(!open)}>{Number(props.month.slice(5))}월 달력 {open?'접기':'펼치기'}<span aria-hidden="true">{open?'−':'+'}</span></button>{open&&<div id={'calendar-'+props.month}><MonthCalendar {...props}/></div>}</div>}
export function MonthCalendar<T extends PeriodEvent>({month,events,onOpen,onExpand,full=false}:{month:string;events:T[];onOpen:(event:T)=>void;onExpand?:()=>void;full?:boolean}){const active=events.filter(e=>intersectsMonth(e,month)),weeks=calendarWeeks(month,active);const now=new Date(),today=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;return <div className={'month-calendar '+(full?'calendar-full':'calendar-mini')} aria-label={month+' 행사기간 달력'}><div className="calendar-caption"><strong>{Number(month.slice(5))}월 행사기간</strong>{!full&&<button onClick={onExpand} aria-label={month+' 달력 크게 보기'}>크게 보기</button>}</div><OwnerLegend events={active}/>{!holidayYearAvailable(month)&&<small className="holiday-note">공휴일 자료 미제공 연도</small>}<div className="calendar-weekdays">{['일','월','화','수','목','금','토'].map(d=><span key={d}>{d}</span>)}</div>{weeks.map(week=>{const hidden=week.segments.filter(s=>s.lane>=2).length;return <div className="calendar-week" key={week.from} style={{gridTemplateRows:`${full?34:20}px repeat(${full?Math.max(1,week.lanes):Math.min(2,Math.max(1,week.lanes))},${full?'24px':'var(--calendar-lane,15px)'}) ${!full&&hidden?'16px':''}`}}><div className="calendar-day-grid">{week.days.map(d=><span className={(d.outside?'outside-day ':'')+((holidayName(d.date)||new Date(d.date+'T12:00:00').getDay()===0)?'holiday-day ':'')+(d.date===today?'calendar-today':'')} key={d.date} title={holidayName(d.date)||undefined} aria-label={d.date+(holidayName(d.date)?" "+holidayName(d.date):"")}>{d.day}{full&&holidayName(d.date)&&<small className="holiday-name">{holidayName(d.date)}</small>}</span>)}</div>{week.segments.filter(s=>full||s.lane<2).map(s=><button key={s.event.id} className={'calendar-event '+divisionClass(s.event.division)+(s.event.status==='완료'?' is-complete':'')+(s.event.status==='진행 중'?' is-progress':'')} style={{background:ownerColor(s.event.owner,s.event.owner_color),gridColumn:`${s.first+1} / ${s.last+2}`,gridRow:s.lane+2}} title={s.event.title+' · '+periodLabel(s.event)+' · '+s.event.division+' · '+s.event.status+' · 담당자: '+ownerName(s.event.owner)} aria-label={s.event.title+' '+periodLabel(s.event)+' 상세 보기'} onClick={()=>onOpen(s.event)}>{s.continuesBefore?'‹ ':''}{s.event.title}{s.continuesAfter?' ›':''}</button>)}{!full&&hidden>0&&<button className="calendar-more" style={{gridColumn:'1 / -1',gridRow:4}} onClick={onExpand}>+{hidden}개 더 보기</button>}</div>})}{full&&!active.length&&<p className="calendar-empty">선택한 조건에 맞는 행사가 없습니다.</p>}</div>}

