 'use client';
import {useEffect,useState} from 'react';
import {ArrowLeft,BookOpen,Pencil,Save,Moon,Sun} from 'lucide-react';
type Document={content:string;version:number;updated:string;editor:string};
export default function Regulations({embedded=false,onDirtyChange,onBusyChange}:{embedded?:boolean;onDirtyChange?:(dirty:boolean)=>void;onBusyChange?:(busy:boolean)=>void}){const [canWrite,setCanWrite]=useState(false);const [document,setDocument]=useState<Document|null>(null),[text,setText]=useState(''),[editing,setEditing]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[dark,setDark]=useState(true);const dirty=document!==null&&text!==document.content;
useEffect(()=>{onDirtyChange?.(dirty)},[dirty,onDirtyChange]);useEffect(()=>{onBusyChange?.(busy)},[busy,onBusyChange]);
useEffect(()=>{const preference=localStorage.getItem('department-theme');const enabled=preference?preference==='dark':true;setDark(enabled);window.document.documentElement.classList.toggle('dark',enabled);void load()},[]);
useEffect(()=>{const guard=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard)},[dirty]);
async function load(){setError('');try{const r=await fetch('/api/regulations');const d=await r.json() as {document:Document;error:string;canEdit?:boolean};if(!r.ok)throw Error(d.error);setDocument(d.document);setText(d.document.content);setCanWrite(d.canEdit===true);setEditing(d.canEdit===true&&!d.document.content)}catch(e){setError((e as Error).message)}}
async function save(){if(!document)return;setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/regulations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content:text,version:document.version})});const d=await r.json() as {document:Document;error:string;canEdit?:boolean};if(!r.ok)throw Error(d.error);setDocument(d.document);setEditing(false);setNotice('내규집을 저장했습니다.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
function theme(){const value=!dark;setDark(value);window.document.documentElement.classList.toggle('dark',value);localStorage.setItem('department-theme',value?'dark':'light')}
return <div className="regulations-page">{!embedded&&<header className="rules-header"><a href="/" className="rules-back"><ArrowLeft size={17}/> 일정실</a><div><BookOpen size={19}/><strong>학과 내규집</strong><span>국립목포대학교 조경학과</span></div><button aria-label={dark?'라이트모드로 전환':'다크모드로 전환'} onClick={theme}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button></header>}<main className="rules-main"><div className="rules-heading"><div><span className="institution-ko">국립목포대학교 조경학과</span><h1>학과 내규집</h1><span className="institution-en">Mokpo National University, Dept of Landscape Architecture</span><p>학과 운영에 필요한 내규를 함께 열람하고 수정합니다.</p></div>{canWrite&&document&&!editing&&<button className="primary" onClick={()=>{setEditing(true);setNotice('')}}><Pencil size={16}/> 내규 수정</button>}</div>{error&&<p className="error" role="alert">{error}{!document&&<button onClick={load}>다시 불러오기</button>}</p>}{notice&&<p className="success" role="status">{notice}</p>}{!document&&!error?<p>내규집을 불러오는 중입니다…</p>:document&&<section className="rules-paper">{editing?<form onSubmit={e=>{e.preventDefault();void save()}}><label htmlFor="rules-content">내규 내용</label><textarea id="rules-content" value={text} disabled={busy} maxLength={100000} onChange={e=>setText(e.target.value)} placeholder="학과 내규를 입력하거나 기존 문서의 텍스트를 붙여 넣으세요. 줄바꿈과 문단이 그대로 저장됩니다."/><div className="rules-save"><span>{text.length.toLocaleString()} / 100,000자{dirty?' · 저장하지 않은 변경사항':''}</span><div><button type="button" disabled={busy} onClick={()=>{setText(document.content);setEditing(false);setError('')}}>취소</button><button type="submit" className="primary" disabled={busy}><Save size={16}/>{busy?'저장 중…':'내규 저장'}</button></div></div></form>:<div className="rules-content">{document.content||'아직 등록된 내규가 없습니다.'}</div>}</section>}{document?.updated&&<p className="rules-updated">마지막 저장 · {new Date(document.updated).toLocaleString('ko-KR')} · {document.editor}</p>}</main></div>}

